name: bank_v
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  another_flushbar: ^1.10.28
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^5.0.2
  google_fonts: ^5.1.0
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

uses-material-design: true

  # To add assets to your application, add an assets section, like this:
assets:
  - assets/
